config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# get "/customers" => ""

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

  # 配送先
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]

  # 注文
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]


  # カート
    resources :cart_items, only: [:index, :update, :destroy, :create]do
      delete 'destroy_all' => 'cart_items#destroy_all'
    end

  # カスタマー
    resources :customers, only: [:show, :edit, :update]do
      member do
        get :unsubscribe
        patch :withdraw
      end
    end

  # 商品
    resources :items, only: [:index, :show]

  end


  namespace :admin do

    # 商品
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # ジャンル
    resources :genres, only: [:index, :create, :edit, :update]

    # 顧客情報
    resources :customers, only: [:index, :show, :edit, :update]

    # 注文
    resources :orders, only: [:index, :show, :update]

    # 製作商品
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence:true
  validates :first_name, presence:true
  validates :last_name_kana, presence:true
  validates :first_name_kana, presence:true
  validates :phone_number, presence:true
  validates :postcode, presence:true, format: {with: /\A[0-9]{7}\z/}
  validates :addresse, presence:true

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
     redirect_to admin_customer_path(@customer)
    else
     render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :addresse, :phone_number, :emai, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h1>Customer Edit</h1>

  <div>
     <%= form_with model: @customer,method: :patch, url: admin_customer_path(@customer) do |f|%>
     <div>
      <table>
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>ふりがな</td>
            <td><%= f.text_field :first_name_kana %></td>
            <td><%= f.text_field :last_name_kana %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= f.text_field :first_name %></td>
            <td><%= f.text_field :last_name %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= f.text_field :postcode %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= f.text_field :addresse %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= f.text_field :phone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= f.email_field :email %>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><%= f.radio_button :is_deleted, :true %>
                <%= f.label :is_deleted, "退会" %>
                <%= f.radio_button :is_deleted, :false %>
                <%= f.label :is_deleted, "有効" %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit "変更を保存",class:"btn btn-outline-dark" %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <%end%>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h1>Customer List</h1>
  <table class="table table-bordered">
    <thead>
      <tr class="table-active">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= "#{customer.first_name}" + "#{customer.last_name}" %></td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted == true %>
                  <%= "退会" %>
                 <% else %>
                  <%= "有効" %>
                 <% end %>
                 </td>
            <td><%= link_to "see more", admin_customer_path(customer.id) %> </td>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <h1>Customer Detail</h1>
  <div class="row">
  <div class="col-6">
  <table class="table">
	<tbody>
		<tr>
			<th>会員ID</th>
			<td><%= @customer.id %></td>
		</tr>
		<tr>
			<th>ふりがな</th>
			<td><%= "#{@customer.first_name_kana}"+"#{@customer.last_name_kana}" %></td>
		</tr>
		<tr>
			<th>氏名</th>
			<td><%= "#{@customer.first_name}"+"#{@customer.last_name}" %></td>
		</tr>
		<tr>
			<th>郵便番号</th>
			<td>〒<%= @customer.postcode %></td>
		</tr>
		<tr>
			<th>住所</th>
			<td><%= @customer.addresse %></td>
		</tr>
		<tr>
			<td>電話番号</td>
			<td><%= @customer.phone_number %></td>
		</tr>
		<tr>
			<th>メールアドレス</th>
			<td><%= @customer.email %></td>
		</tr>
		<tr>
			<th>ステータス</th>
			<td><% if @customer.is_deleted == true %>
                  <%= "退会" %>
                 <% else %>
                  <%= "有効" %>
                 <% end %></td>
		</tr>
	</tbody>
</table>
</div>
</div>
<%= link_to "編集する", edit_admin_customer_path(@customer),class: "btn btn-outline-dark" %>
<%= link_to "会員一覧", admin_customers_path,class: "btn btn-outline-dark" %>