config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# get "/customers" => ""

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

  # 配送先
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]

  # 注文
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]


  # カート
    resources :cart_items, only: [:index, :update, :destroy, :create]do
      delete 'destroy_all' => 'cart_items#destroy_all'
    end

  # カスタマー
    resources :customers, only: [:show, :edit, :update]do
      member do
        get :unsubscribe
        patch :withdraw
      end
    end

  # 商品
    resources :items, only: [:index, :show]

  end


  namespace :admin do

    # 商品
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # ジャンル
    resources :genres, only: [:index, :create, :edit, :update]

    # 顧客情報
    resources :customers, only: [:index, :show, :edit, :update]

    # 注文
    resources :orders, only: [:index, :show, :update]

    # 製作商品
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  validates :post_code, format: {with: /\A[0-9]{7}\z/}
  validates :address,presence:true
  validates :name,presence:true
  validates :payment_method,presence:true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4}

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @q = Order.ransack(params[:q])
    @orders = @q.result(distinct: true)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
      if @order.update(order_params)
        @order_details.update_all(making_status: 0) if @order.order_status == "入金待ち"
        @order_details.update_all(making_status: 1) if @order.order_status == "入金確認"
      end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <h1 class="admin_order">Order List</h1>
  <div class="order_table">
    <table class="table table-bordered col-8">
      <thead>
        <tr class="table-active">
          <th style="width: 20%">購入日時</th>
          <th style="width: 20%">購入者</th>
          <th style="width: 10%">注文個数</th>
          <th style="width: 20%">注文ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M:%S"), admin_order_path(order) %></td>
          <td><%= order.customer.first_name + order.customer.last_name %></td>
          <td><%=order.order_details.sum(:quantity) %>個</td>
          <td><%= order.order_status %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
    <h2 class="admin_order_detail">Order Detail</h2>
    <div class="row">
    <div class="col-8">
    <table class="table">
      <tr>
        <th>購入者</th>
        <td><%= @order.customer.first_name + @order.customer.last_name %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td><%= @order.address %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td>
          <%= form_for (@order), url:admin_order_path(@order), method: :patch, local: true do |f| %>
            <%= f.select :order_status,Order.order_statuses.keys, class: "order_status" %>
            <%= f.submit "変更", class: "btn btn-outline-dark" %>
          <% end %>
        </td>
      </tr>
    </tabls>
    <table class="table table-bordered col-xs-10">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.item_name %></td>
          <td>￥<%= order_detail.order_price %></td>
          <td><%= order_detail.quantity %></td>
          <td>￥<%= order_detail.item.with_tax_price * order_detail.quantity %></td>
          <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch, local: true do |f| %>
              <%= f.hidden_field :order_detail_id, :value => order_detail.id %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys, class: "making_status" %>
              <%= f.submit "変更", class: "btn btn-outline-dark" %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
    <div class="col-4">
      <table class="table">
      <% postage = 800 %>
        <tr>
          <th>商品合計</th>
          <td>￥<%= "#{@order.total_price - postage}" %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td>￥<%= "#{postage}" %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td>￥<%= "#{postage + @order.total_price}" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>