config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# get "/customers" => ""

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

  # 配送先
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]

  # 注文
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]


  # カート
    resources :cart_items, only: [:index, :update, :destroy, :create]do
      delete 'destroy_all' => 'cart_items#destroy_all'
    end

  # カスタマー
    resources :customers, only: [:show, :edit, :update]do
      member do
        get :unsubscribe
        patch :withdraw
      end
    end

  # 商品
    resources :items, only: [:index, :show]

  end


  namespace :admin do

    # 商品
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # ジャンル
    resources :genres, only: [:index, :create, :edit, :update]

    # 顧客情報
    resources :customers, only: [:index, :show, :edit, :update]

    # 注文
    resources :orders, only: [:index, :show, :update]

    # 製作商品
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    # ジャンルの追加に成功した場合、メッセージを表示しジャンル一覧画面へ
    if @genre.save
      flash[:notice] = "ジャンルの追加が完了しました"
      redirect_to admin_genres_path
    # ジャンルの追加に失敗した場合、エラーメッセージを表示しジャンル一覧画面へ
    else
      flash[:alert] = "ジャンルの追加に失敗しました"
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    # ジャンルの更新に成功した場合、メッセージを表示しジャンル一覧画面へ
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルの更新が完了しました"
      redirect_to admin_genres_path
    # ジャンルの更新に失敗した場合、エラーメッセージを表示しジャンル一覧画面へ
    else
      flash[:alert] = "ジャンルの更新に失敗しました"
      redirect_to edit_admin_genre_path
    end
  end

  private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
<h1>Genre Edit</h1>

<%= form_with model: @genre, url: admin_genre_path, local: true, method: :patch do |f| %>
  <div class="field">
    <%= f.text_field :name, autofocus: true %>
  </div>
  <%= f.submit "変更",class: "btn btn-outline-dark" %>
<% end %>
<div class="genre_edit">
<%= link_to "戻る", admin_genres_path,class: "btn btn-outline-dark" %>
</div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
<h1>Genre</h1>

<div class="genre_add">
  <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
  <div class="field">
    <%= f.text_field :name, placeholder: 'ジャンル名' %>
  </div>

    <%= f.submit "ジャンルを追加",class: "btn btn-outline-dark" %>
  <% end %>
</div>
   <div class="row">
    <div class="col-2">
  <table class="table_genre">
    <table class="table table-border-top-bottom mb-5">
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td>
              <%= link_to edit_admin_genre_path(genre.id) do %>
                <%= genre.name %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>
</div>