config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# get "/customers" => ""

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

  # 配送先
    resources :shipping_addresses, only: [:index, :create, :edit, :update, :destroy]

  # 注文
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]


  # カート
    resources :cart_items, only: [:index, :update, :destroy, :create]do
      delete 'destroy_all' => 'cart_items#destroy_all'
    end

  # カスタマー
    resources :customers, only: [:show, :edit, :update]do
      member do
        get :unsubscribe
        patch :withdraw
      end
    end

  # 商品
    resources :items, only: [:index, :show]

  end


  namespace :admin do

    # 商品
    resources :items, only: [:index, :new, :create, :show, :edit, :update]

    # ジャンル
    resources :genres, only: [:index, :create, :edit, :update]

    # 顧客情報
    resources :customers, only: [:index, :show, :edit, :update]

    # 注文
    resources :orders, only: [:index, :show, :update]

    # 製作商品
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :item_id, :quantity, presence: true
  validates :quantity, numericality:{ only_integer: true }

  def subtotal
    item.with_tax_price * quantity
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence:true
  validates :first_name, presence:true
  validates :last_name_kana, presence:true
  validates :first_name_kana, presence:true
  validates :phone_number, presence:true
  validates :postcode, presence:true, format: {with: /\A[0-9]{7}\z/}
  validates :addresse, presence:true

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  belongs_to :genre

  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end

  validates :genre_id, presence: true
  validates :item_name, presence: true, length: { maximum: 20 }
  validates :item_description, presence: true, length: { maximum: 100 }
  validates :price, presence: true
  validates :sales_status, inclusion: { in: [true, false] }
  attribute :sales_status, :boolean, default: false
  validates :image, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  validates :post_code, format: {with: /\A[0-9]{7}\z/}
  validates :address,presence:true
  validates :name,presence:true
  validates :payment_method,presence:true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: {"着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3}
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer
  
  validates :address_name, presence:true
  validates :post_code, presence:true, format: {with: /\A[0-9]{7}\z/}
  validates :address, presence:true
  
  def address_display
   '〒' + post_code + ' ' + address + ' ' + address_name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    # ジャンルの追加に成功した場合、メッセージを表示しジャンル一覧画面へ
    if @genre.save
      flash[:notice] = "ジャンルの追加が完了しました"
      redirect_to admin_genres_path
    # ジャンルの追加に失敗した場合、エラーメッセージを表示しジャンル一覧画面へ
    else
      flash[:alert] = "ジャンルの追加に失敗しました"
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    # ジャンルの更新に成功した場合、メッセージを表示しジャンル一覧画面へ
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルの更新が完了しました"
      redirect_to admin_genres_path
    # ジャンルの更新に失敗した場合、エラーメッセージを表示しジャンル一覧画面へ
    else
      flash[:alert] = "ジャンルの更新に失敗しました"
      redirect_to edit_admin_genre_path
    end
  end

  private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.all
  end

  def new
    # ジャンルが空なら先にジャンル登録を促しジャンル追加画面へ
    if Genre.count.zero?
      flash[:alert] = "先にジャンルを追加してください"
      redirect_to admin_genres_path
    # ジャンルが登録されていれば商品新規登録画面へ
    else
      @item = Item.new
    end
  end

  def create
    @item = Item.new(item_params)
    # 商品が登録されればメッセージを表示し商品一覧ページへ遷移
    if @item.save
      flash[:notice] = "商品の登録が完了しました"
      redirect_to admin_item_path(@item)
    # 商品の登録が失敗すればエラーメッセージを表示し再度商品の新規登録画面を表示
    else
      flash[:alert] = "商品の登録に失敗しました"
      redirect_to new_admin_item_path
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    # 情報更新が成功すればメッセージを表示し商品一覧ページへ遷移
    if @item.update(item_params)
      flash[:notice] = "商品情報の更新が完了しました"
      redirect_to admin_items_path
    # 情報更新が失敗すればエラーメッセージを表示し再度商品情報編集画面を表示
    else
      flash[:alert] = "商品情報の更新に失敗しました"
      redirect_to edit_admin_item_path
    end
  end

  private
    def item_params
      params.require(:item).permit(:item_name, :item_description, :price, :image, :sales_status, :genre_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
 <footer class="text-center text-white footer" style="background-color:#192436">
   <%= image_tag 'naganocake.logo.jpg', size: "240x80" %>
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Images -->
    <section class="">
      <div class="row">
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://imageslabo.com/wp-content/uploads/2019/05/397_sweets_cake_mont-blanc_6859.jpg"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://cdn.pixabay.com/photo/2019/02/03/11/21/waffles-3972360_1280.jpg"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://cdn.pixabay.com/photo/2017/08/02/13/10/drink-2571544_1280.jpg"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://imageslabo.com/wp-content/uploads/2019/05/395_sweets_chocolate-cake_6856.jpg"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://cdn.pixabay.com/photo/2020/12/17/10/15/cheesecake-5838900_1280.jpg"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://imageslabo.com/wp-content/uploads/2019/05/205_chocolate_bread-cake_6596.jpg"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
      </div>
    </section>
    <!-- Section: Images -->
  </div>
  <!-- Grid container -->
　　<%= link_to new_admin_session_path ,class: 'nav-link text-light' do %>
      Admin page
    <% end %>
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar navbar-expand-lg navbar-derk p-4 header-logo" style="background-color:#192436" id="h-nav">

    <a class="navbar-brand" href="/">
    <%= image_tag 'naganocake.logo.jpg', size: "300x100" %>
  </a>
      <% if customer_signed_in? %>
      <a class="navbar-brand text-light" href="/"><span>Welcome <%= current_customer.first_name %>！</span></a>
      <% elsif admin_signed_in? %>
      <a class="navbar-brand text-light" href="/"><span>Admin Page</span></a>
      <% else %>
      <a class="navbar-brand text-light" href="/"><span>Welcome guest！</span></a>
      <% end %>
      </ul>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-center" id="navbar1">
        <ul class="navbar-nav ml-auto mr-auto">
        <% if customer_signed_in? %>
        <!--カスタマーがログインしている時 -->
          <li>
            <%= link_to customer_path(current_customer),class: 'nav-link text-light' do %>
            MY PAGE<br>
            マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to items_path,class: 'nav-link text-light' do %>
            PRODUCTS<br>
            商品一覧
            <% end %>
          </li>
          <li>
            <%=  link_to cart_items_path ,class: 'nav-link text-light' do %>
            CART<br>
            カート
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>
            LOGOUT<br>
            ログアウト
            <% end %>
          </li>
        <% elsif admin_signed_in? %>
        <!-- 管理者がログインしている時 -->
          <li>
            <%=  link_to admin_items_path,class: 'nav-link text-light' do %>
            PRODUCTS<br>
            商品一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_customers_path,class: 'nav-link text-light' do %>
            CUSTOMERS<br>
            会員一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_orders_path,class: 'nav-link text-light' do %>
            ORDERS<br>
            注文履歴一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_genres_path,class: 'nav-link text-light' do %>
            GENRES<br>
            ジャンル一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-light' do %>
            LOGOUT<br>
            ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
            About<br>
            店舗紹介
            <% end %>
          </li>
          <li>
            <%= link_to items_path,class: 'nav-link text-light' do %>
            PRODUCTS<br>
            商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
            SIGNUP<br>
            新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>
            LOGIN<br>
            ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
      </div>
    </div>
  </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom' %>
  </head>


  <body data-spy="scroll" data-target="#h-nav" data-offset="86" >
<!--ヘッダー-->
  <header>
    <%= render "layouts/header" %>



   <div class="main">
     <!--フラッシュメッセージ-->
     <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
     <% end %>
     <!--メインコンテンツ-->
     <%= yield %>
   </div>

    <div class="footerFixed">

  <%= render "layouts/footer" %>
    </div>
  </body>
</html>